apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.pakka
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring
            port:
              number: 80


