apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-boot-app
        image: devopsjaya536/img1:v1
        ports:
        - containerPort: 8080
